site_name: Arctic
site_description: Arctic is a pluggable streaming lakehouse service layer on top of hive and iceberg

docs_dir: '../../docs/en'
site_dir: '../../generated/en'
remote_name: arctic-site
use_directory_urls: true
repo_url: https://github.com/NetEase/arctic
repo_name: NetEase/arctic
edit_uri: ""

# pip install mkdocs-material
theme:
  font:
    text: sans-serif
  name: material
  language: en
  favicon: images/favicon.ico
  logo: images/arctic_banner.png
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github

extra:
  search:
    language: 'en'
  alternate:
    - name: 中文
      link: /ch/
      lang: zh-Hant
    - name: English
      link: /en/
      lang: en

copyright: "Copyright 2018-2021"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Concepts:
    - Catalogs: concepts/catalogs.md
    - Self-optimizing: concepts/self-optimizing.md
    - Table Watermark: concepts/table-watermark.md
  - Admin Guides:
    - Deployment: guides/deployment.md
    - Managing Catalogs: guides/managing-catalogs.md
    - Managing Tables: guides/managing-tables.md
    - Managing Optimizers: guides/managing-optimizers.md
    - Using Kyuubi By Terminal: guides/using-kyuubi.md
    - Metrics: guides/metrics.md
  - Configurations: configurations.md
  - Formats:
      - Overview: formats/overview.md
      - Iceberg: formats/iceberg.md
      - Mixed Iceberg: formats/mixed-iceberg.md
      - Mixed Hive: formats/mixed-hive.md
  - Engines:
    - Overview: engines/overview.md
    - Trino: engines/trino.md
    - Spark:
        - Get Started: engines/spark/spark-get-started.md
        - Configurations: engines/spark/spark-conf.md
        - Spark DDL: engines/spark/spark-ddl.md
        - Spark Queries: engines/spark/spark-queries.md
        - Spark Writes: engines/spark/spark-writes.md
    - Flink:
        - Get Started: engines/flink/flink-get-started.md
        - Flink DDL: engines/flink/flink-ddl.md
        - Flink DML: engines/flink/flink-dml.md
        - Flink DataStream: engines/flink/flink-ds.md
        - Using LogStore: engines/flink/using-logstore.md

plugins:
  - search

extra_css:
  - stylesheets/extra.css
